// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91gszS5vg2O0tgSR2fsnWKQQL1Ta55OA',
    appId: '1:891872442975:web:30aacf30959a4b381739ea',
    messagingSenderId: '891872442975',
    projectId: 'expenses-tracker-8e89c',
    authDomain: 'expenses-tracker-8e89c.firebaseapp.com',
    databaseURL: 'https://expenses-tracker-8e89c-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-tracker-8e89c.firebasestorage.app',
    measurementId: 'G-413DV1MMH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXlhs0sNfdMqsmN5QaRZTXJvO1yUAKqs',
    appId: '1:891872442975:android:7eedb4122ef3b41e1739ea',
    messagingSenderId: '891872442975',
    projectId: 'expenses-tracker-8e89c',
    databaseURL: 'https://expenses-tracker-8e89c-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-tracker-8e89c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-6HK9rmxGIAPlrV8AyqWj_0k-Ss_CXw',
    appId: '1:891872442975:ios:7301ad2c0fce55b61739ea',
    messagingSenderId: '891872442975',
    projectId: 'expenses-tracker-8e89c',
    databaseURL: 'https://expenses-tracker-8e89c-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-tracker-8e89c.firebasestorage.app',
    iosBundleId: 'com.example.skillday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-6HK9rmxGIAPlrV8AyqWj_0k-Ss_CXw',
    appId: '1:891872442975:ios:7301ad2c0fce55b61739ea',
    messagingSenderId: '891872442975',
    projectId: 'expenses-tracker-8e89c',
    databaseURL: 'https://expenses-tracker-8e89c-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-tracker-8e89c.firebasestorage.app',
    iosBundleId: 'com.example.skillday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91gszS5vg2O0tgSR2fsnWKQQL1Ta55OA',
    appId: '1:891872442975:web:94140199a578c6de1739ea',
    messagingSenderId: '891872442975',
    projectId: 'expenses-tracker-8e89c',
    authDomain: 'expenses-tracker-8e89c.firebaseapp.com',
    databaseURL: 'https://expenses-tracker-8e89c-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-tracker-8e89c.firebasestorage.app',
    measurementId: 'G-MHTEKQ9G6L',
  );
}
